# Day12

# Numpy liberary

In [4]:
import numpy as np

In [10]:
print(np.__version__) # version pata karna ka liya

1.26.4


# Create a numpy ndarray object

numpy is used to work with array. the array object in numpy is calld ndarray
we can create a numpy ndarray objet by using the array() function.

In [18]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# to create an ndarray, we can pass a list, tuple or any array like object into the array() method, and it will be convert into ndarray.

# use a tuple to create a numpy array:

In [23]:
arr = np.array((1,23,43,"vivek",True))
print(arr)
print(type(arr))

['1' '23' '43' 'vivek' 'True']
<class 'numpy.ndarray'>


# Dimensional in arrays

0-D Array 0-D arrays, or scalars, are the element in array each value in an array is a 0-D array.

Create a 0-D array with value 20

In [29]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim) # dimension pata karna ka liya

20
<class 'numpy.ndarray'>
0


# 1-D Array

In [33]:
arr = np.array([12,23,54,76,87])
print(arr)
print(arr.ndim)

[12 23 54 76 87]
1


# Creating 2-D array

In [38]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [40]:
arr = np.array([[1,2,3,4,"vivek"],[5,6,7,8,True]])
print(arr)
print(type(arr))
print(arr.ndim)

[['1' '2' '3' '4' 'vivek']
 ['5' '6' '7' '8' 'True']]
<class 'numpy.ndarray'>
2


In [42]:
arr = np.array([[1,2,0.3,4],[5.6,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1.  2.  0.3 4. ]
 [5.6 6.  7.  8. ]]
<class 'numpy.ndarray'>
2


# 3-D array

In [51]:
arr = np.array([[[1,3.2 ,2,True],[4,6,5,987]],[[4,87,90,False],[12,32,43,23]]])
print(arr)
print(arr.ndim)
print(type(arr))
print(len(arr))

[[[  1.    3.2   2.    1. ]
  [  4.    6.    5.  987. ]]

 [[  4.   87.   90.    0. ]
  [ 12.   32.   43.   23. ]]]
3
<class 'numpy.ndarray'>
2


In [53]:
arr = np.array([[[1,3.2 ,2,True],[4,6,5,987],[4,87,90,False]]])
print(arr)
print(arr.ndim)
print(type(arr))
print(len(arr))

[[[  1.    3.2   2.    1. ]
  [  4.    6.    5.  987. ]
  [  4.   87.   90.    0. ]]]
3
<class 'numpy.ndarray'>
1


# Check numbe of Dimension

In [62]:
a = np.array(42)
b = np.array([1,2,3,4,5,7])
c = np.array([[1,2,3],[3,5,7]])
d = np.array([[[1,2,3],[4,5,6]],[[8,7,6],[6,5,4]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# hish dimension array

an array can have any number of dimension

when the array is created , you can define the number of dimension by using the ndmin argument.

# creating an array with 5 Dimension and varify that it has 5 Dimension

In [73]:
arr = np.array([1, 2, 4, 5, 6], ndmin = 5)
print(arr)
print('number of Dimension :', arr.ndim)

[[[[[1 2 4 5 6]]]]]
number of Dimension : 5


In [75]:
arr = np.array([[[[[1, 2 ,4, 5 ,6]]]]])
print(arr)
print(arr.ndim)

[[[[[1 2 4 5 6]]]]]
5


# numpy array indexing

arry indeing is the same as accessing an array element

you can access an array elementby refring to its index number

the indexs in numpy arrays start with 0, meaning that the first element has index 0 and the second has index 1 etc..

# Get the first element from the array

In [80]:
arr = np.array([12,43,54,67,87,132,43])
print(arr[4])

87


# Get third and sixth ant 8th element from the folloeing array and add them

In [83]:
arr = np.array([12,13,14,15,16,17,18,19,22,33,44,55,66,88,90])
print("the third element is:", arr[2])
print("the sisth element is:", arr[5])
print("the 8th element is:", arr[7])
print("the sum of the element are:", arr[2]+arr[5]+arr[7])

the third element is: 14
the sisth element is: 17
the 8th element is: 19
the sum of the element are: 50


# Accessing 2-d arrays

to access element from 2-D arrays we use comma seprated integers representing the dimension and the index of the elememnt.

think pog 2-D array like a tabel ewith row and column, where the dimension seperate the row and the i ndex seperate the column.

In [89]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print("2nd element in 1st row:" , arr[0,1])

2nd element in 1st row: 2


In [91]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print("4th element in 1st row:" , arr[0,3])

4th element in 1st row: 4


In [95]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print("1st element in 2nd row:" , arr[1,0])

1st element in 2nd row: 22


In [99]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print("last element in 1st row:" , arr[1,5])

last element in 1st row: 7


# add the first element of row 1 and last element

In [102]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print("first element in 1st row:" , arr[0,0])
print("last element of second row:", arr[1,5])
print("sum is:", arr[0,0] +arr[1,5])

first element in 1st row: 1
last element of second row: 7
sum is: 8


# accessing 3-D arrays

to access element from 3-D array we can use comma seperated integers representing the dimension and the index of the element

# accessing the third element of the second array of the first array:

In [107]:
arr = np.array([[[1,3.2 ,2,True],[4,6,5,987]],[[4,87,90,False],[12,32,43,23]]])
print(arr[0,1,2])

5.0


In [111]:
arr = np.array([[[1,3.2 ,2,True],[4,6,5,987]],[[4,87,90,False],[12,32,43,23]]])
print(arr[1,0,1])

87.0


In [115]:
arr = np.array([[[1,3.2 ,2,True],[4,6,5,987]],[[4,87,90,False],[12,32,43,23]]])
print(arr[1,1,1])

32.0


In [119]:
arr = np.array([[[1,3.2 ,2,True],[4,6,5,987]],[[4,87,90,False],[12,32,43,23]]])
print(arr[0,0,1])

3.2


# negative indexing

using negative indexing to access an array from the end.

In [123]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print("last array of second dim:" , arr[1,-1])

last array of second dim: 7


# Numpy array slicing

slicing in python means taking element from one givin index to another iven index

we pass slice instead of index like this:[start:end].

we can also define the step, like this: [start:end:step].

# slice element from index 1 to index 5 from the followinf array

In [130]:
arr = np.array([1,2,3,4,5,34,22,23,22,45,8,7])
print(arr[1:5])

[2 3 4 5]


slicing element from index 4 to the end of array

In [133]:
arr = np.array([1,2,3,4,5,34,22,23,22,45,8,7])
print(arr[4:])

[ 5 34 22 23 22 45  8  7]


In [135]:
arr = np.array([1,2,3,4,5,34,22,23,22,45,8,7])
print(arr[::2])

[ 1  3  5 22 22  8]


# Slicing 2-D arrays

In [138]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print(arr[1,0:4])

[22 23 22 45]


In [144]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print(arr[0,1:2])

[2]


In [146]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print(arr[0,0:3])

[1 2 3]


# From both element return index 2

In [149]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print(arr[0:2,2])

[ 3 22]


# slice index 1 to index 4 (not included), this will return a 2-D array

In [152]:
arr = np.array([[1,2,3,4,5,34],[22,23,22,45,8,7]])
print(arr[0:2,1:4])

[[ 2  3  4]
 [23 22 45]]
