# Numpy part 2

# Day 13

SLICING OF NUMPY ARRAY

In [10]:
import numpy as np

In [12]:
arr = np.array([1,34,54,67,34,11])
print(arr[0:3])

[ 1 34 54]


In [14]:
arr = np.array([1,34,54,67,34,11,44,87,89,90])
print(arr[0:9:2])

[ 1 54 34 44 89]


# Slicing in 2D arrays

In [25]:
arr = np.array([[12,32,44,33,23,45,65,89],[121,33,44,55,66,77,88,90]])
print(arr[1,2:4])

[44 55]


In [27]:
arr = np.array([[12,32,44,33,23,45,65,89],[121,33,44,55,66,77,88,90]])
print(arr[0,0:4])

[12 32 44 33]


# numpy part 2 staet

data type in python by default python have these data types:

sting,integer,boolean,float

In [ ]:
Data type in numpy 

numpy has some extera data type, ard refer to data type with one character, list of these

i= integer
b= boolean
u = unsigned integer
f = float
c = complex float
m = timedelta
M = datetime 
o = object
s = string
U = unicode string
v = fixed chuck of memory for other type (void)

# check the data type of an array

In [32]:
import numpy as np

In [34]:
arr = np.array([12,44,54,67,88,90])
print(arr.dtype)

int32


In [36]:
arr = np.array(["vivek",True ,"rastogi",12,34.5])
print(arr.dtype)

<U32


In [40]:
arr = np.array(["vivek",True ,"rastogi",12])
print(arr.dtype)

<U11


In [42]:
arr = np.array(["vivek",True ,"rastogi","sharma"])
print(arr.dtype)

<U7


In [44]:
arr = np.array(["vivek","tranner" ,"rastogi",12])
print(arr.dtype)

<U11


In [46]:
arr = np.array(["vivek","tranner" ,"rastogi","123","True"])
print(arr.dtype)

<U7


In [48]:
arr = np.array(["vivek","rastogi"])
print(arr.dtype)

<U7


# Create array with a difend data type

In [51]:
arr = np.array([12,43,56,33,44,556,11], dtype = 'f')
print(arr)
print(arr.dtype)

[ 12.  43.  56.  33.  44. 556.  11.]
float32


In [53]:
arr = np.array([12,43,56,33,44,556,11], dtype = 'S')
print(arr)
print(arr.dtype)

[b'12' b'43' b'56' b'33' b'44' b'556' b'11']
|S3


In [55]:
arr = np.array([12,43,56,33,44,556,11], dtype = 'c')
print(arr)
print(arr.dtype)

[b'1' b'4' b'5' b'3' b'4' b'5' b'1']
|S1


In [59]:
arr = np.array([12,43,56,33,44,556,11], dtype = 'b')
print(arr)
print(arr.dtype)

[12 43 56 33 44 44 11]
int8


C:\Users\vivek rastogi\AppData\Local\Temp\ipykernel_680\1172547126.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 556 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([12,43,56,33,44,556,11], dtype = 'b')


# creating an array with datatype 4byte integer

In [64]:
arr = np.array([12,55,76,88,90,33,22,123], dtype = 'i4')
print(arr)
print(arr.dtype)

[ 12  55  76  88  90  33  22 123]
int32


# numpy arrays shape

the shape of an array is the number of element in each dimension

# print the shape of the 2-D arrays

In [78]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [81]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[11,44,66,77]]])
print(arr.shape)

(1, 3, 4)


# create n array with 5 dimension using ndmin using a vector with values 1,2,3,4 and varify that last dimension has value 4:


In [84]:
arr = np.array([1 ,2 ,3 ,4], ndmin = 5)
print(arr)
print(" shape of array:", arr.shape)

[[[[[1 2 3 4]]]]]
 shape of array: (1, 1, 1, 1, 4)


# joining numpy array

In [95]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1 , arr2))
print(arr)

[1 2 3 4 5 6 7 8]


# join teo 2-D array along rows (axis = 1): Rows

In [101]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1 , arr2) , axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [103]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1 , arr2) , axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting numpy as arrays

# splliting is reverse function of joinning

joing merges multipal arrays into one and spliting break one arry into multipal

# split the array in three part

In [109]:
arr = ([12,34,56,78,90,11,22,33,44,55,65])
newarr = np.array_split(arr,3)
print(newarr)

[array([12, 34, 56, 78]), array([90, 11, 22, 33]), array([44, 55, 65])]


In [111]:
# split array into four pats
arr = ([12,34,56,78,90,11,22,33,44,55,65])
newarr = np.array_split(arr,4)
print(newarr)

[array([12, 34, 56]), array([78, 90, 11]), array([22, 33, 44]), array([55, 65])]


# ravel and flatten - converts multidimensional array into 1-d array

In [118]:
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,0],[0,9,8,7,6],[5,4,3,2,1]]]])
print(arr)
print("dimension is :" , arr.ndim)
arr1 = arr.ravel()
print(arr1)
print("new dimension is :",arr1.ndim)

[[[[1 2 3 4 5]
   [6 7 8 9 0]
   [0 9 8 7 6]
   [5 4 3 2 1]]]]
dimension is : 4
[1 2 3 4 5 6 7 8 9 0 0 9 8 7 6 5 4 3 2 1]
new dimension is : 1


# arithmatic operation in numpy arrays

# addition

In [122]:
arr = np.array([1,2,3,4,5])
y = arr+2
print(y)

[3 4 5 6 7]


In [126]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
y = arr+arr2
print(y)

[ 7  9 11 13  5]


In [130]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
y = np.add(arr,arr2)
print(y)

[ 7  9 11 13  5]


# subtraction

In [133]:
arr = np.array([1,2,3,4,5])
y = arr-2
print(y)

[-1  0  1  2  3]


In [135]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
y = arr-arr2
print(y)

[-5 -5 -5 -5  5]


In [139]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
y = np.subtract(arr,arr2a
print(y)

[-5 -5 -5 -5  5]


# Multiplication

In [142]:
arr = np.array([1,2,3,4,5])
y = arr*2
print(y)

[ 2  4  6  8 10]


In [144]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
y = arr*arr2
print(y)

[ 6 14 24 36  0]


In [150]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
y = np.multiply(arr,arr2)
print(y)

[ 6 14 24 36  0]


# Division

In [153]:
arr = np.array([1,2,3,4,5])
y = arr/2
print(y)

[0.5 1.  1.5 2.  2.5]


In [157]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,2])
y = arr/arr2
print(y)

[0.16666667 0.28571429 0.375      0.44444444 2.5       ]


In [161]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,2])
y = np.divide(arr,arr2)
print(y)

[0.16666667 0.28571429 0.375      0.44444444 2.5       ]


# Modulous

In [164]:
arr = np.array([1,2,3,4,5])
y = arr%2
print(y)

[1 0 1 0 1]


In [166]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,2])
y = arr%arr2
print(y)

[1 2 3 4 1]


In [168]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,2])
y = np.mod(arr,arr2)
print(y)

[1 2 3 4 1]


# Arithmatic operation on 2d array

In [171]:
arr1 = np.array([[12,23,34,45,56],[22,44,66,77,88]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
x = arr1-arr2
print(x)

[[11 21 31 41 51]
 [16 37 58 68 85]]


In [173]:
arr1 = np.array([[12,23,34,45,56],[22,44,66,77,88]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
x = arr1*arr2
print(x)

[[ 12  46 102 180 280]
 [132 308 528 693 264]]


In [175]:
arr1 = np.array([[12,23,34,45,56],[22,44,66,77,88]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
x = arr1/arr2
print(x)

[[12.         11.5        11.33333333 11.25       11.2       ]
 [ 3.66666667  6.28571429  8.25        8.55555556 29.33333333]]


In [177]:
arr1 = np.array([[12,23,34,45,56],[22,44,66,77,88]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
x = arr1+arr2
print(x)

[[13 25 37 49 61]
 [28 51 74 86 91]]


In [179]:
arr1 = np.array([[12,23,34,45,56],[22,44,66,77,88]])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
x = arr1%arr2
print(x)

[[0 1 1 1 1]
 [4 2 2 5 1]]


# arithmatic opration 3 D array

In [182]:
arr1 = np.array([[[12,23,34,45,56],[22,44,66,77,88],[11,34,2,5,4]]])
arr2 = np.array([[[1,2,3,4,5],[43,6,7,8,9],[6,7,8,9,3]]])
x = arr1-arr2
print(x)

[[[ 11  21  31  41  51]
  [-21  38  59  69  79]
  [  5  27  -6  -4   1]]]


In [184]:
arr1 = np.array([[[12,23,34,45,56],[22,44,66,77,88],[11,34,2,5,4]]])
arr2 = np.array([[[1,2,3,4,5],[43,6,7,8,9],[6,7,8,9,3]]])
x = arr1+arr2
print(x)

[[[13 25 37 49 61]
  [65 50 73 85 97]
  [17 41 10 14  7]]]


In [186]:
arr1 = np.array([[[12,23,34,45,56],[22,44,66,77,88],[11,34,2,5,4]]])
arr2 = np.array([[[1,2,3,4,5],[43,6,7,8,9],[6,7,8,9,3]]])
x = arr1/arr2
print(x)

[[[12.         11.5        11.33333333 11.25       11.2       ]
  [ 0.51162791  7.33333333  9.42857143  9.625       9.77777778]
  [ 1.83333333  4.85714286  0.25        0.55555556  1.33333333]]]


In [188]:
arr1 = np.array([[[12,23,34,45,56],[22,44,66,77,88],[11,34,2,5,4]]])
arr2 = np.array([[[1,2,3,4,5],[43,6,7,8,9],[6,7,8,9,3]]])
x = arr1*arr2
print(x)

[[[ 12  46 102 180 280]
  [946 264 462 616 792]
  [ 66 238  16  45  12]]]


In [190]:
arr1 = np.array([[[12,23,34,45,56],[22,44,66,77,88],[11,34,2,5,4]]])
arr2 = np.array([[[1,2,3,4,5],[43,6,7,8,9],[6,7,8,9,3]]])
x = arr1%arr2
print(x)

[[[ 0  1  1  1  1]
  [22  2  3  5  7]
  [ 5  6  2  5  1]]]


# Unique function

In [193]:
arr = np.array([1,2,33,22,4,66,55,44,33,1,2,3,4,5,1,2,7,6,5,8,45,8,7,9,0,8,7])
print(arr)
y = np.unique(arr)
print(y)

[ 1  2 33 22  4 66 55 44 33  1  2  3  4  5  1  2  7  6  5  8 45  8  7  9
  0  8  7]
[ 0  1  2  3  4  5  6  7  8  9 22 33 44 45 55 66]


In [195]:
arr = np.array([1,2,33,22,4,66,55,44,33,1,2,3,4,5,1,2,7,6,5,8,45,8,7,9,0,8,7])
print(arr)
y = np.unique(arr, return_index = True)
print(y)

[ 1  2 33 22  4 66 55 44 33  1  2  3  4  5  1  2  7  6  5  8 45  8  7  9
  0  8  7]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 22, 33, 44, 45, 55, 66]), array([24,  0,  1, 11,  4, 13, 17, 16, 19, 23,  3,  2,  7, 20,  6,  5],
      dtype=int64))


In [197]:
arr = np.array([1,2,33,22,4,66,55,44,33,1,2,3,4,5,1,2,7,6,5,8,45,8,7,9,0,8,7])
print(arr)
y = np.unique(arr, return_counts = True)
print(y)

[ 1  2 33 22  4 66 55 44 33  1  2  3  4  5  1  2  7  6  5  8 45  8  7  9
  0  8  7]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 22, 33, 44, 45, 55, 66]), array([1, 3, 3, 1, 2, 2, 1, 3, 3, 1, 1, 2, 1, 1, 1, 1], dtype=int64))


# Delete

In [204]:
arr = np.array([1,2,33,22,4,66,55,44,33,1,2,3])
arr1 = np.delete(arr,[6])
print(arr1)

[ 1  2 33 22  4 66 44 33  1  2  3]


In [210]:
arr = np.array([[12,3,44,55,66,55],[11,44,55,66,77,44],[77,55,66,87,99,90]])
print(arr)
arr1 = np.delete(arr,1 , axis = 0)
print()
print(arr1)

[[12  3 44 55 66 55]
 [11 44 55 66 77 44]
 [77 55 66 87 99 90]]

[[12  3 44 55 66 55]
 [77 55 66 87 99 90]]
